- name: create jenkins jobs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - frontend
      - cart
      - catalogue
      - user
      - shipping
      - payment
  roles:
    - jenkins-jobs